export interface CategoryItem {
  id: string;
  name: string;
  bnName: string;
  icon: string;
  subcategories: { id: string; name: string; bnName: string }[];
}

export const MAIN_CATEGORIES: CategoryItem[] = [
  {
    id: 'property',
    name: 'Property',
    bnName: 'প্রপার্টি',
    icon: 'Home',
    subcategories: [
      { id: 'apartment', name: 'Apartment / Flat', bnName: 'অ্যাপার্টমেন্ট / ফ্ল্যাট' },
      { id: 'house', name: 'Independent House', bnName: 'বাড়ি' },
      { id: 'room', name: 'Single Room', bnName: 'সিঙ্গেল রুম' },
      { id: 'mess', name: 'Bachelor Mess / Sublet', bnName: 'ব্যাচেলর মেস / সাবলেট' },
      { id: 'hostel', name: 'Student Hostel', bnName: 'ছাত্র/ছাত্রী হোস্টেল' },
      { id: 'shop', name: 'Commercial Shop', bnName: 'দোকান' },
      { id: 'office', name: 'Office Space', bnName: 'অফিস স্পেস' },
      { id: 'warehouse', name: 'Warehouse / Godown', bnName: 'গুদামঘর' },
      { id: 'land', name: 'Land / Plot', bnName: 'জমি / প্লট' },
    ],
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    bnName: 'মার্কেটপ্লেস',
    icon: 'ShoppingBag',
    subcategories: [
      { id: 'mobile', name: 'Mobiles & Accessories', bnName: 'মোবাইল ও অ্যাকসেসরিজ' },
      { id: 'laptop', name: 'Laptops & Computers', bnName: 'ল্যাপটপ ও কম্পিউটার' },
      { id: 'electronics', name: 'Electronics & TV', bnName: 'ইলেকট্রনিক্স' },
      { id: 'vehicles', name: 'Vehicles & Bikes', bnName: 'গাড়ি ও মোটরসাইকেল' },
      { id: 'furniture', name: 'Home & Office Furniture', bnName: 'আসবাবপত্র' },
      { id: 'clothing', name: 'Fashion & Clothing', bnName: 'পোশাক ও ফ্যাশন' },
      { id: 'agriculture', name: 'Agriculture & Farm', bnName: 'কৃষি ও খামার' },
      { id: 'appliances', name: 'Home Appliances', bnName: 'গৃহস্থালী সামগ্রী' },
      { id: 'books', name: 'Books & Stationery', bnName: 'বই ও স্টেশনারি' },
    ],
  },
  {
    id: 'services',
    name: 'Services',
    bnName: 'সেবাসমূহ',
    icon: 'Wrench',
    subcategories: [
      { id: 'electrician', name: 'Electrician', bnName: 'ইলেকট্রিশিয়ান' },
      { id: 'plumber', name: 'Plumber', bnName: 'প্লাম্বার' },
      { id: 'ac_technician', name: 'AC / Fridge Technician', bnName: 'এসি ও ফ্রিজ মেকানিক' },
      { id: 'carpenter', name: 'Carpenter', bnName: 'কাঠমিস্ত্রি' },
      { id: 'cleaner', name: 'Home Cleaning', bnName: 'বাড়ি ক্লিনিং' },
      { id: 'cook', name: 'Cook / Chef', bnName: 'বাবুর্চি / রাঁধুনি' },
      { id: 'driver', name: 'Driver', bnName: 'ড্রাইভার' },
      { id: 'painter', name: 'House Painter', bnName: 'রংমিস্ত্রি' },
      { id: 'pest_control', name: 'Pest Control', bnName: 'পোকামাকড় দমন' },
      { id: 'cctv_security', name: 'CCTV & Security', bnName: 'সিসিটিভি ও সিকিউরিটি' },
    ],
  },
  {
    id: 'professionals',
    name: 'Professionals',
    bnName: 'পেশাজীবী',
    icon: 'UserCheck',
    subcategories: [
      { id: 'doctor', name: 'Doctor & Specialist', bnName: 'ডাক্তার ও বিশেষজ্ঞ' },
      { id: 'dentist', name: 'Dentist', bnName: 'ডেন্টিস্ট' },
      { id: 'lawyer', name: 'Lawyer & Legal Advisor', bnName: 'আইনজীবী' },
      { id: 'accountant', name: 'Chartered Accountant', bnName: 'হিসাবরক্ষক' },
      { id: 'engineer', name: 'Civil / Structural Engineer', bnName: 'প্রকৌশলী' },
      { id: 'architect', name: 'Architect', bnName: 'স্থপতি' },
      { id: 'tutor', name: 'Teacher / Academic Tutor', bnName: 'শিক্ষক / গৃহশিক্ষক' },
      { id: 'consultant', name: 'Business Consultant', bnName: 'বিজনেস কনসালটেন্ট' },
    ],
  },
  {
    id: 'freelance',
    name: 'Freelancing',
    bnName: 'ফ্রিল্যান্সিং',
    icon: 'Code',
    subcategories: [
      { id: 'web_dev', name: 'Web Development', bnName: 'ওয়েব ডেভেলপমেন্ট' },
      { id: 'app_dev', name: 'Mobile App Development', bnName: 'মোবাইল অ্যাপ ডেভেলপমেন্ট' },
      { id: 'graphic_design', name: 'Graphic Design & Branding', bnName: 'গ্রাফিক ডিজাইন' },
      { id: 'ui_ux', name: 'UI / UX Design', bnName: 'ইউআই / ইউএক্স' },
      { id: 'seo_marketing', name: 'SEO & Digital Marketing', bnName: 'ডিজিটাল মার্কেটিং' },
      { id: 'content_writing', name: 'Content & Copywriting', bnName: 'কন্টেন্ট রাইটিং' },
      { id: 'video_editing', name: 'Video Editing & Motion', bnName: 'ভিডিও এডিটিং' },
      { id: 'ai_services', name: 'AI & Data Services', bnName: 'এআই ও ডেটা সার্ভিস' },
    ],
  },
  {
    id: 'jobs',
    name: 'Jobs',
    bnName: 'চাকরি',
    icon: 'Briefcase',
    subcategories: [
      { id: 'it_software', name: 'IT & Software', bnName: 'আইটি ও সফটওয়্যার' },
      { id: 'sales_marketing', name: 'Sales & Marketing', bnName: 'সেলস ও মার্কেটিং' },
      { id: 'accounting_finance', name: 'Accounting & Finance', bnName: 'অ্যাকাউন্টিং ও ফিন্যান্স' },
      { id: 'education_teaching', name: 'Education & Training', bnName: 'শিক্ষা ও প্রশিক্ষণ' },
      { id: 'healthcare', name: 'Healthcare & Medical', bnName: 'চিকিৎসা ও স্বাস্থ্য' },
      { id: 'customer_support', name: 'Customer Support', bnName: 'কাস্টমার সাপোর্ট' },
      { id: 'logistics_delivery', name: 'Delivery & Logistics', bnName: 'ডেলিভারি ও লজিস্টিক' },
      { id: 'hospitality', name: 'Hotel & Restaurant', bnName: 'হোটেল ও রেস্তোরাঁ' },
    ],
  },
  {
    id: 'business',
    name: 'Businesses',
    bnName: 'ব্যবসা ও প্রতিষ্ঠান',
    icon: 'Store',
    subcategories: [
      { id: 'restaurant_cafe', name: 'Restaurant & Cafe', bnName: 'রেস্তোরাঁ ও ক্যাফে' },
      { id: 'grocery_supermarket', name: 'Grocery & Supermarket', bnName: 'মুদি ও সুপারশপ' },
      { id: 'pharmacy_diagnostic', name: 'Pharmacy & Diagnostics', bnName: 'ফার্মেসি ও ডায়াগনস্টিক' },
      { id: 'salon_spa', name: 'Beauty Salon & Spa', bnName: 'সেলুন ও পার্লার' },
      { id: 'auto_repair', name: 'Automobile Workshop', bnName: 'গাড়ি মেরামত কারখানা' },
      { id: 'hardware_building', name: 'Hardware & Sanitary', bnName: 'হার্ডওয়্যার ও স্যানিটারি' },
    ],
  },
];

export const LOCATIONS_DATA = [
  {
    division: 'Dhaka',
    bnDivision: 'ঢাকা',
    cities: [
      {
        name: 'Dhaka City',
        bnName: 'ঢাকা সিটি',
        lat: 23.8103,
        lng: 90.4125,
        areas: ['Gulshan', 'Banani', 'Dhanmondi', 'Uttara', 'Mirpur', 'Mohammadpur', 'Motijheel', 'Bashundhara', 'Badda', 'Old Dhaka'],
      },
      {
        name: 'Gazipur',
        bnName: 'গাজীপুর',
        lat: 23.9999,
        lng: 90.4203,
        areas: ['Chowrasta', 'Joydebpur', 'Tongi', 'Konabari'],
      },
      {
        name: 'Narayanganj',
        bnName: 'নারায়ণগঞ্জ',
        lat: 23.6238,
        lng: 90.5000,
        areas: ['Chashara', 'Siddhirganj', 'Fatullah'],
      },
    ],
  },
  {
    division: 'Khulna',
    bnDivision: 'খুলনা',
    cities: [
      {
        name: 'Khulna City',
        bnName: 'খুলনা সিটি',
        lat: 22.8456,
        lng: 89.5403,
        areas: ['Shibbari', 'Sonadanga', 'Boyra', 'Khalishpur', 'Daulatpur', 'Rupsha', 'Nirala', 'Mujgunni'],
      },
      {
        name: 'Jashore',
        bnName: 'যশোর',
        lat: 23.1664,
        lng: 89.2081,
        areas: ['Kotwali', 'Doratana', 'Chowrasta', 'New Market'],
      },
      {
        name: 'Kushtia',
        bnName: 'কুষ্টিয়া',
        lat: 23.9013,
        lng: 89.1205,
        areas: ['Mojompur', 'Court Para', 'Thanapara'],
      },
    ],
  },
  {
    division: 'Chattogram',
    bnDivision: 'চট্টগ্রাম',
    cities: [
      {
        name: 'Chattogram City',
        bnName: 'চট্টগ্রাম সিটি',
        lat: 22.3569,
        lng: 91.7832,
        areas: ['Agrabad', 'GEC Circle', 'Nasirabad', 'Panchlaish', 'Halishahar', 'Chawkbazar', 'Khulshi'],
      },
      {
        name: 'Cox\'s Bazar',
        bnName: 'কক্সবাজার',
        lat: 21.4272,
        lng: 92.0058,
        areas: ['Kolatoli', 'Laboni Beach', 'Main Road'],
      },
    ],
  },
  {
    division: 'Rajshahi',
    bnDivision: 'রাজশাহী',
    cities: [
      {
        name: 'Rajshahi City',
        bnName: 'রাজশাহী সিটি',
        lat: 24.3636,
        lng: 88.6241,
        areas: ['Shaheb Bazar', 'Motihar', 'Kazla', 'Upashahar'],
      },
      {
        name: 'Bogura',
        bnName: 'বগুড়া',
        lat: 24.8465,
        lng: 89.3777,
        areas: ['Shatmatha', 'Jaleshwaritola', 'Banani'],
      },
    ],
  },
  {
    division: 'Sylhet',
    bnDivision: 'সিলেট',
    cities: [
      {
        name: 'Sylhet City',
        bnName: 'সিলেট সিটি',
        lat: 24.8949,
        lng: 91.8687,
        areas: ['Zindabazar', 'Amberkhana', 'Subidbazar', 'Shahi Eidgah', 'Upashahar'],
      },
    ],
  },
];

export const TRANSLATIONS = {
  en: {
    findEverything: 'Find Everything. Connect Everyone.',
    searchPlaceholder: 'What are you looking for? (e.g. 2BHK flat, Electrician, Laptop, React Dev)',
    chooseLocation: 'Choose location',
    searchBtn: 'Search',
    exploreNearby: 'Explore Nearby',
    allListings: 'All Discoveries',
    property: 'Property',
    marketplace: 'Marketplace',
    services: 'Services',
    professionals: 'Professionals',
    jobs: 'Jobs',
    freelance: 'Freelancing',
    businesses: 'Businesses',
    communities: 'Communities',
    events: 'Events',
    iNeed: 'I Need',
    mapView: 'Map View',
    listView: 'List View',
    nearMe: 'Near Me',
    safetyWarning: 'Safety Alert: Always verify identity and inspect items in person before sending advance payments.',
    addNew: '+ Add',
    login: 'Log In',
    register: 'Sign Up',
    logout: 'Sign Out',
    myDashboard: 'Dashboard',
    myProfile: 'My Profile',
    settings: 'Settings',
    adminPanel: 'Admin Hub',
    messages: 'Messages',
    notifications: 'Notifications',
    saved: 'Saved Items',
    save: 'Save',
    savedAlready: 'Saved',
    contact: 'Contact',
    message: 'Message',
    bookNow: 'Book Appointment',
    applyJob: 'Apply for Job',
    sendProposal: 'Send Proposal',
    createListing: 'Create Discovery Listing',
    postRequest: 'Post What You Need',
    socialFeed: 'Social Feed',
    createPost: 'Create Post',
    reviews: 'Reviews & Ratings',
    writeReview: 'Write Review',
    verification: 'Get Verified',
    shareCard: 'Share Digital Card',
    aiAssistant: 'FindX AI Hub',
    noListingsYet: 'No listings yet in this view.',
    beTheFirst: 'Be the first to create one!',
    verified: 'Verified',
  },
  bn: {
    findEverything: 'সব খুঁজুন। সবাইকে জুড়ুন।',
    searchPlaceholder: 'আপনি কী খুঁজছেন? (যেমন: ২ রুমের বাসা, ইলেকট্রিশিয়ান, ল্যাপটপ, ড্রাইভার)',
    chooseLocation: 'এলাকা বেছে নিন',
    searchBtn: 'অনুসন্ধান',
    exploreNearby: 'আশেপাশের খুঁজুন',
    allListings: 'সকল তালিকা',
    property: 'প্রপার্টি ও বাসাভাড়া',
    marketplace: 'মার্কেটপ্লেস',
    services: 'সেবাসমূহ',
    professionals: 'পেশাজীবী',
    jobs: 'চাকরি',
    freelance: 'ফ্রিল্যান্সিং',
    businesses: 'ব্যবসা ও শপ',
    communities: 'কমিউনিটি',
    events: 'ইভেন্ট',
    iNeed: 'আমার প্রয়োজন (I Need)',
    mapView: 'ম্যাপ ভিউ',
    listView: 'লিস্ট ভিউ',
    nearMe: 'কাছাকাছি',
    safetyWarning: 'নিরাপত্তা বার্তা: অগ্রিম টাকা পাঠানোর আগে ব্যক্তিগতভাবে যাচাই করে নিন।',
    addNew: '+ যোগ করুন',
    login: 'লগইন',
    register: 'রেজিস্ট্রেশন',
    logout: 'লগআউট',
    myDashboard: 'ড্যাশবোর্ড',
    myProfile: 'আমার প্রোফাইল',
    settings: 'সেটিংস',
    adminPanel: 'অ্যাডমিন প্যানেল',
    messages: 'মেসেজ',
    notifications: 'বিজ্ঞপ্তি',
    saved: 'সংরক্ষিত',
    save: 'সেভ',
    savedAlready: 'সংরক্ষিত',
    contact: 'যোগাযোগ',
    message: 'মেসেজ পাঠান',
    bookNow: 'অ্যাপয়েন্টমেন্ট বুকিং',
    applyJob: 'আবেদন করুন',
    sendProposal: 'প্রস্তাব পাঠান',
    createListing: 'লিস্টিং তৈরি করুন',
    postRequest: 'আপনার কী দরকার পোস্ট করুন',
    socialFeed: 'সামাজিক ফিড',
    createPost: 'পোস্ট তৈরি করুন',
    reviews: 'রিভিউ ও রেটিং',
    writeReview: 'রিভিউ লিখুন',
    verification: 'ভেরিফাই করুন',
    shareCard: 'ডিজিটাল কার্ড শেয়ার',
    aiAssistant: 'ফাইন্ডএক্স এআই হাব',
    noListingsYet: 'এখনও কোনো লিস্টিং পাওয়া যায়নি।',
    beTheFirst: 'প্রথম লিস্টিংটি আপনিই তৈরি করুন!',
    verified: 'ভেরিফাইড',
  },
};
